# -*- coding: utf-8 -*-
"""1271.엄청난 부자2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZUkVlT-H1ls1rryZddm_ZFhVdJCfET0m
"""

# 1271. 엄청난 부자2

money, num = map(int, input().split())
print(money//num)
print(money%num)
